spring:
  application:
    name: designer-toys-user-service
  cloud:
    bootstrap:
      enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 2d269f5a-321b-43a5-a369-24c5c74c6c2c
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: 2d269f5a-321b-43a5-a369-24c5c74c6c2c
        file-extension: yaml
        prefix: ${spring.application.name}
        refresh-enabled: true
        timeout: 3000
  profiles:
    active: dev

logging:
  level:
    com.alibaba.cloud.nacos: debug
